import React from 'react'

function FAQ() {



    const faq = [
        {
            question: 'What is PlasmaWorld?',
            answer: 'PlasmaWorld is a revolutionary NFT project that aims to create a comprehensive ecosystem for NFT holders. By utilizing funds generated from NFT sales, we plan to establish a diverse range of businesses, including web3-based affiliate marketing, real estate investments, sustainable farming initiatives, production companies, and open-source development for our NFT community. Our goal is to empower our NFT holders with a range of sustainable technology solutions and opportunities for growth.',
        },
        {
            question: 'What are the Benefits from Holding the PlasmaWorld?',
            answer: 'The 19,800 Plasma World Foundations NFTs in circulation embody a 20% ownership slice of the expansive ecosystem. Holders of these NFTs not only receive a proportional share of the quarterly cash flow but also unlock the prospect of becoming active business owners. These NFTs open the door for individuals to engage in a community-driven ecosystem, fostering the exchange of ideas and collaborative development, ultimately empowering them to shape and thrive within innovative ventures.',
        },
        {
            question: 'How does PlasmaW3bWorld use the funds we Generate from the Ecosystem?',
            answer: "We're on a mission to make our mark as one of the biggest NFT ecosystems globally. To make it happen, we've set up a cool system with seven wallets, each getting a specific slice. The Ecosystem wallet (Wallet 1) is the big earner, grabbing 63% of the cash flow. Our Charity wallet (Wallet 2) gets a solid 9%. Then, we've got Wallets 4, 5, and 6 exclusively for three special NFTs, each getting their 9%. Toss in the Iotex Delegate Wallet with its 1%, and you've got the full picture.This way of divvying up the funds isn't just about being transparent; it's about making sure the community drives the show and the ecosystem meets everyone's needs.",
        },
        {
            question: 'How does PlasmaWorldFoundation Pay the Nft Holders?',
            answer: 'PlasmaWorld pays its NFT holders on a quarterly basis by distributing a proportionate share of the revenue generated by the ecosystem. The distribution is based on the percentage of NFTs held by each individual.. This distribution system allows for a fair and transparent distribution of funds, and ensures that all NFT holders have the opportunity to benefit from the success of the ecosystem.',
        },


    ]





    return (
        <div className=' py-24 lg:py-32 text-white'>
            <div className='max-w-7xl mx-auto px-7 wxl:px-0'>
                <h2 className='text-3xl text-sky-500  text-center font-bold'>
                    FAQ
                </h2>


                <div className='my-10'>
                    {
                        faq.map((item, index) => (
                            <div key={index} className="collapse collapse-arrow bg-base-200 mb-2">
                                <input type="radio" name="my-accordion-2" />
                                <div className="collapse-title text-lg font-medium">
                                    {item.question}
                                </div>
                                <div className="collapse-content">
                                    <p className='text-sky-500'>
                                        {item.answer}
                                    </p>
                                </div>
                            </div>
                        ))
                    }
                </div>


            </div>
        </div>
    )
}

export default FAQ